version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: company_ai_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: ["python", "bot.py"]

  admin:
    build: .
    container_name: company_admin_panel
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "admin.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    image: nginx:alpine
    container_name: company_admin_frontend
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin

volumes:
  pgdata: